[Service]
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
RestrictAddressFamilies=AF_UNIX
RestrictNamespaces=true
MemoryMax=16M
SystemCallFilter=@system-service
SystemCallFilter=read write epoll_pwait recvmsg sendmsg close connect socket
BusPolicy=deny
TimeoutStopSec=5s
KillSignal=SIGTERM
